### ISSUE TITLE
jobsystem后碰撞如何处理

### ISSUE THREAD

**Issue by ditianxin** [dreamfairy/Unity-DynamicBone-JobSystem-Opmized#1]
首先感谢分享，我现在有个关于jobsystem后关于碰撞的问题请教，原来的dynamicbone中是在UpdateParticles2中处理碰撞问题的，想问下jobsystem后还能在UpdateParticle2Job中处理碰撞问题吗？该如何处理？

即原代码UpdateParticles2中的这一部分：
            // collide
            if (m_Colliders != null)
            {
                float particleRadius = p.m_Radius * m_ObjectScale;
                for (int j = 0; j < m_Colliders.Count; ++j)
                {
                    DynamicBoneColliderBase c = m_Colliders[j];
                    if (c != null && c.enabled)                    
                        p.m_isCollide |= c.Collide(ref p.m_Position, particleRadius);                    
                }
            }
怎么放到jobsystem中处理，谢谢

**Comment by dreamfairy** [comment]
> 首先感谢分享，我现在有个关于jobsystem后关于碰撞的问题请教，原来的dynamicbone中是在UpdateParticles2中处理碰撞问题的，想问下jobsystem后还能在UpdateParticle2Job中处理碰撞问题吗？该如何处理？
> 
> 即原代码UpdateParticles2中的这一部分：
> // collide
> if (m_Colliders != null)
> {
> float particleRadius = p.m_Radius * m_ObjectScale;
> for (int j = 0; j < m_Colliders.Count; ++j)
> {
> DynamicBoneColliderBase c = m_Colliders[j];
> if (c != null && c.enabled)
> p.m_isCollide |= c.Collide(ref p.m_Position, particleRadius);
> }
> }
> 怎么放到jobsystem中处理，谢谢

sorry,文章相关的项目 都不会进行维护。 尝试构造SphereCollider 类似的Struct 数据类型，统一存到NativeArray里进行批次计算
